export type CountryPhone = {
  name: string;
  code: string;
  iso: string;
  flag: string;
  mask: (string | RegExp)[] | null;
  placeholder: string;
};

export type Country = {
  name: string;
  code: string;
  flag?: string;
};

const flagModules = import.meta.glob<{ default: string }>("../assets/flags/*.png", { eager: true });

function getFlagUrl(iso: string): string {
  const match = Object.entries(flagModules).find(([path]) => path.endsWith(`/${iso}.png`));
  return match ? match[1].default : "";
}

const PRIORITY_COUNTRIES = ["Alemanha", "Brasil", "Espanha", "França", "Itália", "Portugal", "Suíça"];

function byPriorityThenAlphabetical(a: { name: string }, b: { name: string }): number {
  const aPriority = PRIORITY_COUNTRIES.indexOf(a.name);
  const bPriority = PRIORITY_COUNTRIES.indexOf(b.name);

  if (aPriority !== -1 || bPriority !== -1) {
    if (aPriority === -1) return 1;
    if (bPriority === -1) return -1;
    return aPriority - bPriority;
  }

  return a.name.localeCompare(b.name, "pt-BR");
}

export const COUNTRY_PHONES: CountryPhone[] = [
    {
        name: "Afeganistão",
        code: "+93",
        iso: "AF",
        flag: getFlagUrl("af"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "700 123 456",
    },
    {
        name: "África do Sul",
        code: "+27",
        iso: "ZA",
        flag: getFlagUrl("za"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "82 123 4567",
    },
    {
        name: "Albânia",
        code: "+355",
        iso: "AL",
        flag: getFlagUrl("al"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "672 123 456",
    },
    {
        name: "Alemanha",
        code: "+49",
        iso: "DE",
        flag: getFlagUrl("de"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "151 234 5678",
    },
    {
        name: "Andorra",
        code: "+376",
        iso: "AD",
        flag: getFlagUrl("ad"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "312 345",
    },
    {
        name: "Angola",
        code: "+244",
        iso: "AO",
        flag: getFlagUrl("ao"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "923 123 456",
    },
    {
        name: "Antígua e Barbuda",
        code: "+1",
        iso: "AG",
        flag: getFlagUrl("ag"),
        mask: [
            "(",
            /\d/,
            /\d/,
            /\d/,
            ")",
            " ",
            /\d/,
            /\d/,
            /\d/,
            "-",
            /\d/,
            /\d/,
            /\d/,
            /\d/,
        ],
        placeholder: "(268) 464-1234",
    },
    {
        name: "Arábia Saudita",
        code: "+966",
        iso: "SA",
        flag: getFlagUrl("sa"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "50 123 4567",
    },
    {
        name: "Argélia",
        code: "+213",
        iso: "DZ",
        flag: getFlagUrl("dz"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "555 12 3456",
    },
    {
        name: "Argentina",
        code: "+54",
        iso: "AR",
        flag: getFlagUrl("ar"),
        mask: [
            "(",
            /\d/,
            /\d/,
            ")",
            " ",
            /\d/,
            /\d/,
            /\d/,
            /\d/,
            "-",
            /\d/,
            /\d/,
            /\d/,
            /\d/,
        ],
        placeholder: "(11) 2345-6789",
    },
    {
        name: "Armênia",
        code: "+374",
        iso: "AM",
        flag: getFlagUrl("am"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "91 234 567",
    },
    {
        name: "Austrália",
        code: "+61",
        iso: "AU",
        flag: getFlagUrl("au"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "0412 345 678",
    },
    {
        name: "Áustria",
        code: "+43",
        iso: "AT",
        flag: getFlagUrl("at"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "664 123 4567",
    },
    {
        name: "Azerbaijão",
        code: "+994",
        iso: "AZ",
        flag: getFlagUrl("az"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "50 123 45 67",
    },
    {
        name: "Bahamas",
        code: "+1",
        iso: "BS",
        flag: getFlagUrl("bs"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(242) 359-1234",
    },
    {
        name: "Bahrein",
        code: "+973",
        iso: "BH",
        flag: getFlagUrl("bh"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "3600 1234",
    },
    {
        name: "Bangladesh",
        code: "+880",
        iso: "BD",
        flag: getFlagUrl("bd"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "01712 345678",
    },
    {
        name: "Barbados",
        code: "+1",
        iso: "BB",
        flag: getFlagUrl("bb"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(246) 250-1234",
    },
    {
        name: "Bélgica",
        code: "+32",
        iso: "BE",
        flag: getFlagUrl("be"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "470 12 34 56",
    },
    {
        name: "Belize",
        code: "+501",
        iso: "BZ",
        flag: getFlagUrl("bz"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "622-1234",
    },
    {
        name: "Benin",
        code: "+229",
        iso: "BJ",
        flag: getFlagUrl("bj"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "90 12 34 56",
    },
    {
        name: "Bielorrússia",
        code: "+375",
        iso: "BY",
        flag: getFlagUrl("by"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, "-", /\d/, /\d/],
        placeholder: "29 123-45-67",
    },
    {
        name: "Bolívia",
        code: "+591",
        iso: "BO",
        flag: getFlagUrl("bo"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "712 34567",
    },
    {
        name: "Bósnia e Herzegovina",
        code: "+387",
        iso: "BA",
        flag: getFlagUrl("ba"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/],
        placeholder: "61 234-567",
    },
    {
        name: "Botsuana",
        code: "+267",
        iso: "BW",
        flag: getFlagUrl("bw"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "71 234 567",
    },
    {
        name: "Brasil",
        code: "+55",
        iso: "BR",
        flag: getFlagUrl("br"),
        mask: [
            "(",
            /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(11) 99999-9999",
    },
    {
        name: "Brunei",
        code: "+673",
        iso: "BN",
        flag: getFlagUrl("bn"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "712 3456",
    },
    {
        name: "Bulgária",
        code: "+359",
        iso: "BG",
        flag: getFlagUrl("bg"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "888 123 456",
    },
    {
        name: "Burkina Faso",
        code: "+226",
        iso: "BF",
        flag: getFlagUrl("bf"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "70 12 34 56",
    },
    {
        name: "Burundi",
        code: "+257",
        iso: "BI",
        flag: getFlagUrl("bi"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "79 123 456",
    },
    {
        name: "Cabo Verde",
        code: "+238",
        iso: "CV",
        flag: getFlagUrl("cv"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "991 2345",
    },
    {
        name: "Camarões",
        code: "+237",
        iso: "CM",
        flag: getFlagUrl("cm"),
        mask: [/\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "6 71 23 45 67",
    },
    {
        name: "Camboja",
        code: "+855",
        iso: "KH",
        flag: getFlagUrl("kh"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "12 345 678",
    },
    {
        name: "Canadá",
        code: "+1",
        iso: "CA",
        flag: getFlagUrl("ca"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(416) 555-1234",
    },
    {
        name: "Catar",
        code: "+974",
        iso: "QA",
        flag: getFlagUrl("qa"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "3312 3456",
    },
    {
        name: "Cazaquistão",
        code: "+7",
        iso: "KZ",
        flag: getFlagUrl("kz"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/,
            "-",
            /\d/, /\d/,
        ],
        placeholder: "(701) 123-45-67",
    },
    {
        name: "Chade",
        code: "+235",
        iso: "TD",
        flag: getFlagUrl("td"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "63 12 34 56",
    },
    {
        name: "Chile",
        code: "+56",
        iso: "CL",
        flag: getFlagUrl("cl"),
        mask: [/\d/, " ", /\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "9 1234 5678",
    },
    {
        name: "China",
        code: "+86",
        iso: "CN",
        flag: getFlagUrl("cn"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "138 1234 5678",
    },
    {
        name: "Chipre",
        code: "+357",
        iso: "CY",
        flag: getFlagUrl("cy"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "96 123 456",
    },
    {
        name: "Colômbia",
        code: "+57",
        iso: "CO",
        flag: getFlagUrl("co"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "310 123 4567",
    },
    {
        name: "Comores",
        code: "+269",
        iso: "KM",
        flag: getFlagUrl("km"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "321 23 45",
    },
    {
        name: "Congo",
        code: "+242",
        iso: "CG",
        flag: getFlagUrl("cg"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "06 123 4567",
    },
    {
        name: "República Democrática do Congo",
        code: "+243",
        iso: "CD",
        flag: getFlagUrl("cd"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "812 345 678",
    },
    {
        name: "Coreia do Norte",
        code: "+850",
        iso: "KP",
        flag: getFlagUrl("kp"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "19 123 4567",
    },
    {
        name: "Coreia do Sul",
        code: "+82",
        iso: "KR",
        flag: getFlagUrl("kr"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "10 1234 5678",
    },
    {
        name: "Costa do Marfim",
        code: "+225",
        iso: "CI",
        flag: getFlagUrl("ci"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "07 12 34 56",
    },
    {
        name: "Costa Rica",
        code: "+506",
        iso: "CR",
        flag: getFlagUrl("cr"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "8312-3456",
    },
    {
        name: "Croácia",
        code: "+385",
        iso: "HR",
        flag: getFlagUrl("hr"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "91 234 5678",
    },
    {
        name: "Cuba",
        code: "+53",
        iso: "CU",
        flag: getFlagUrl("cu"),
        mask: [/\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "5 1234567",
    },
    {
        name: "Dinamarca",
        code: "+45",
        iso: "DK",
        flag: getFlagUrl("dk"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "20 12 34 56",
    },
    {
        name: "Djibouti",
        code: "+253",
        iso: "DJ",
        flag: getFlagUrl("dj"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "77 12 34 56",
    },
    {
        name: "Dominica",
        code: "+1",
        iso: "DM",
        flag: getFlagUrl("dm"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(767) 225-1234",
    },
    {
        name: "Egito",
        code: "+20",
        iso: "EG",
        flag: getFlagUrl("eg"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "100 123 4567",
    },
    {
        name: "El Salvador",
        code: "+503",
        iso: "SV",
        flag: getFlagUrl("sv"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "7123-4567",
    },
    {
        name: "Emirados Árabes Unidos",
        code: "+971",
        iso: "AE",
        flag: getFlagUrl("ae"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "50 123 4567",
    },
    {
        name: "Equador",
        code: "+593",
        iso: "EC",
        flag: getFlagUrl("ec"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "99 123 4567",
    },
    {
        name: "Eritreia",
        code: "+291",
        iso: "ER",
        flag: getFlagUrl("er"),
        mask: [/\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "7 123456",
    },
    {
        name: "Eslováquia",
        code: "+421",
        iso: "SK",
        flag: getFlagUrl("sk"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "905 123 456",
    },
    {
        name: "Eslovênia",
        code: "+386",
        iso: "SI",
        flag: getFlagUrl("si"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "31 234 567",
    },
    {
        name: "Espanha",
        code: "+34",
        iso: "ES",
        flag: getFlagUrl("es"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "612 345 678",
    },
    {
        name: "Estados Unidos",
        code: "+1",
        iso: "US",
        flag: getFlagUrl("us"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(212) 555-1234",
    },
    {
        name: "Estônia",
        code: "+372",
        iso: "EE",
        flag: getFlagUrl("ee"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "5123 4567",
    },
    {
        name: "Eswatini",
        code: "+268",
        iso: "SZ",
        flag: getFlagUrl("sz"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "76 123 456",
    },
    {
        name: "Etiópia",
        code: "+251",
        iso: "ET",
        flag: getFlagUrl("et"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "91 234 5678",
    },
    {
        name: "Fiji",
        code: "+679",
        iso: "FJ",
        flag: getFlagUrl("fj"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "701 2345",
    },
    {
        name: "Filipinas",
        code: "+63",
        iso: "PH",
        flag: getFlagUrl("ph"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "917 123 4567",
    },
    {
        name: "Finlândia",
        code: "+358",
        iso: "FI",
        flag: getFlagUrl("fi"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "40 123 4567",
    },
    {
        name: "França",
        code: "+33",
        iso: "FR",
        flag: getFlagUrl("fr"),
        mask: [
            /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/,
        ],
        placeholder: "06 12 34 56 78",
    },
    {
        name: "Gabão",
        code: "+241",
        iso: "GA",
        flag: getFlagUrl("ga"),
        mask: [
            /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/,
        ],
        placeholder: "06 12 34 56",
    },
    {
        name: "Gâmbia",
        code: "+220",
        iso: "GM",
        flag: getFlagUrl("gm"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/,
        ],
        placeholder: "301 2345",
    },
    {
        name: "Gana",
        code: "+233",
        iso: "GH",
        flag: getFlagUrl("gh"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/,
        ],
        placeholder: "241 234 567",
    },
    {
        name: "Geórgia",
        code: "+995",
        iso: "GE",
        flag: getFlagUrl("ge"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/,
        ],
        placeholder: "555 12 34 56",
    },
    {
        name: "Granada",
        code: "+1",
        iso: "GD",
        flag: getFlagUrl("gd"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(473) 403-1234",
    },
    {
        name: "Grécia",
        code: "+30",
        iso: "GR",
        flag: getFlagUrl("gr"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/,
        ],
        placeholder: "691 2345 678",
    },
    {
        name: "Guatemala",
        code: "+502",
        iso: "GT",
        flag: getFlagUrl("gt"),
        mask: [
            /\d/, /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "5123-4567",
    },
    {
        name: "Guiana",
        code: "+592",
        iso: "GY",
        flag: getFlagUrl("gy"),
        mask: [
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "609-1234",
    },
    {
        name: "Guiné",
        code: "+224",
        iso: "GN",
        flag: getFlagUrl("gn"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, " ",
            /\d/, /\d/, /\d/,
        ],
        placeholder: "621 12 3456",
    },
    {
        name: "Guiné Equatorial",
        code: "+240",
        iso: "GQ",
        flag: getFlagUrl("gq"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/,
        ],
        placeholder: "222 123 456",
    },
    {
        name: "Guiné-Bissau",
        code: "+245",
        iso: "GW",
        flag: getFlagUrl("gw"),
        mask: [
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/, /\d/, " ",
            /\d/, /\d/,
        ],
        placeholder: "955 1234",
    },
    {
        name: "Haiti",
        code: "+509",
        iso: "HT",
        flag: getFlagUrl("ht"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "3412-3456",
    },
    {
        name: "Honduras",
        code: "+504",
        iso: "HN",
        flag: getFlagUrl("hn"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "9123-4567",
    },
    {
        name: "Hungria",
        code: "+36",
        iso: "HU",
        flag: getFlagUrl("hu"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "20 123 4567",
    },
    {
        name: "Iêmen",
        code: "+967",
        iso: "YE",
        flag: getFlagUrl("ye"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "711 234 567",
    },
    {
        name: "Ilhas Marshall",
        code: "+692",
        iso: "MH",
        flag: getFlagUrl("mh"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "235-1234",
    },
    {
        name: "Ilhas Salomão",
        code: "+677",
        iso: "SB",
        flag: getFlagUrl("sb"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "7421234",
    },
    {
        name: "Índia",
        code: "+91",
        iso: "IN",
        flag: getFlagUrl("in"),
        mask: [
            /\d/, /\d/, /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "98765 43210",
    },
    {
        name: "Indonésia",
        code: "+62",
        iso: "ID",
        flag: getFlagUrl("id"),
        mask: [
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "812-345-6789",
    },
    {
        name: "Irã",
        code: "+98",
        iso: "IR",
        flag: getFlagUrl("ir"),
        mask: [
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "912 345 6789",
    },
    {
        name: "Iraque",
        code: "+964",
        iso: "IQ",
        flag: getFlagUrl("iq"),
        mask: [
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "770 123 4567",
    },
    {
        name: "Irlanda",
        code: "+353",
        iso: "IE",
        flag: getFlagUrl("ie"),
        mask: [
            /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "85 123 4567",
    },
    {
        name: "Islândia",
        code: "+354",
        iso: "IS",
        flag: getFlagUrl("is"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "611 1234",
    },
    {
        name: "Israel",
        code: "+972",
        iso: "IL",
        flag: getFlagUrl("il"),
        mask: [
            /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "50-123-4567",
    },
    {
        name: "Itália",
        code: "+39",
        iso: "IT",
        flag: getFlagUrl("it"),
        mask: [
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/,
            " ",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "312 345 6789",
    },
    {
        name: "Jamaica",
        code: "+1",
        iso: "JM",
        flag: getFlagUrl("jm"),
        mask: [
            "(",
            /\d/, /\d/, /\d/,
            ")",
            " ",
            /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "(876) 210-1234",
    },
    {
        name: "Japão",
        code: "+81",
        iso: "JP",
        flag: getFlagUrl("jp"),
        mask: [
            /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
            "-",
            /\d/, /\d/, /\d/, /\d/,
        ],
        placeholder: "90-1234-5678",
    },
    {
        name: "Jordânia",
        code: "+962",
        iso: "JO",
        flag: getFlagUrl("jo"),
        mask: [/\d/, " ", /\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "7 9012 3456",
    },
    {
        name: "Kiribati",
        code: "+686",
        iso: "KI",
        flag: getFlagUrl("ki"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "72000",
    },
    {
        name: "Kosovo",
        code: "+383",
        iso: "XK",
        flag: getFlagUrl("xk"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "44 123 456",
    },
    {
        name: "Kuwait",
        code: "+965",
        iso: "KW",
        flag: getFlagUrl("kw"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "5000 1234",
    },
    {
        name: "Laos",
        code: "+856",
        iso: "LA",
        flag: getFlagUrl("la"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "20 123 4567",
    },
    {
        name: "Lesoto",
        code: "+266",
        iso: "LS",
        flag: getFlagUrl("ls"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "5012 3456",
    },
    {
        name: "Letônia",
        code: "+371",
        iso: "LV",
        flag: getFlagUrl("lv"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "2123 4567",
    },
    {
        name: "Líbano",
        code: "+961",
        iso: "LB",
        flag: getFlagUrl("lb"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "71 123 456",
    },
    {
        name: "Libéria",
        code: "+231",
        iso: "LR",
        flag: getFlagUrl("lr"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "77 123 456",
    },
    {
        name: "Líbia",
        code: "+218",
        iso: "LY",
        flag: getFlagUrl("ly"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "91 234 5678",
    },
    {
        name: "Liechtenstein",
        code: "+423",
        iso: "LI",
        flag: getFlagUrl("li"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "660 1234",
    },
    {
        name: "Lituânia",
        code: "+370",
        iso: "LT",
        flag: getFlagUrl("lt"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "612 34567",
    },
    {
        name: "Luxemburgo",
        code: "+352",
        iso: "LU",
        flag: getFlagUrl("lu"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "621 123 456",
    },
    {
        name: "Macedônia do Norte",
        code: "+389",
        iso: "MK",
        flag: getFlagUrl("mk"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "70 123 456",
    },
    {
        name: "Madagascar",
        code: "+261",
        iso: "MG",
        flag: getFlagUrl("mg"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "32 12 345 67",
    },
    {
        name: "Malásia",
        code: "+60",
        iso: "MY",
        flag: getFlagUrl("my"),
        mask: [/\d/, /\d/, "-", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "12-345 6789",
    },
    {
        name: "Malawi",
        code: "+265",
        iso: "MW",
        flag: getFlagUrl("mw"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "9912 34567",
    },
    {
        name: "Maldivas",
        code: "+960",
        iso: "MV",
        flag: getFlagUrl("mv"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "771-2345",
    },
    {
        name: "Mali",
        code: "+223",
        iso: "ML",
        flag: getFlagUrl("ml"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "65 12 34 56",
    },
    {
        name: "Malta",
        code: "+356",
        iso: "MT",
        flag: getFlagUrl("mt"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "9912 3456",
    },
    {
        name: "Marrocos",
        code: "+212",
        iso: "MA",
        flag: getFlagUrl("ma"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "612-34-5678",
    },
    {
        name: "Maurícia",
        code: "+230",
        iso: "MU",
        flag: getFlagUrl("mu"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "5251-2345",
    },
    {
        name: "Mauritânia",
        code: "+222",
        iso: "MR",
        flag: getFlagUrl("mr"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "22 34 56 78",
    },
    {
        name: "México",
        code: "+52",
        iso: "MX",
        flag: getFlagUrl("mx"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "55 1234 5678",
    },
    {
        name: "Micronésia",
        code: "+691",
        iso: "FM",
        flag: getFlagUrl("fm"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "320-1234",
    },
    {
        name: "Moçambique",
        code: "+258",
        iso: "MZ",
        flag: getFlagUrl("mz"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "84 123 4567",
    },
    {
        name: "Moldávia",
        code: "+373",
        iso: "MD",
        flag: getFlagUrl("md"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/],
        placeholder: "62 123-456",
    },
    {
        name: "Mônaco",
        code: "+377",
        iso: "MC",
        flag: getFlagUrl("mc"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "06 12 34 56",
    },
    {
        name: "Mongólia",
        code: "+976",
        iso: "MN",
        flag: getFlagUrl("mn"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "8812-3456",
    },
    {
        name: "Montenegro",
        code: "+382",
        iso: "ME",
        flag: getFlagUrl("me"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "67 123 456",
    },
    {
        name: "Myanmar",
        code: "+95",
        iso: "MM",
        flag: getFlagUrl("mm"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "912345678",
    },
    {
        name: "Namíbia",
        code: "+264",
        iso: "NA",
        flag: getFlagUrl("na"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "81 123 4567",
    },
    {
        name: "Nauru",
        code: "+674",
        iso: "NR",
        flag: getFlagUrl("nr"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/],
        placeholder: "555-1234",
    },
    {
        name: "Nepal",
        code: "+977",
        iso: "NP",
        flag: getFlagUrl("np"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "984-1234567",
    },
    {
        name: "Nicarágua",
        code: "+505",
        iso: "NI",
        flag: getFlagUrl("ni"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "8888-1234",
    },
    {
        name: "Níger",
        code: "+227",
        iso: "NE",
        flag: getFlagUrl("ne"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "93 12 34 56",
    },
    {
        name: "Nigéria",
        code: "+234",
        iso: "NG",
        flag: getFlagUrl("ng"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "803 123 4567",
    },
    {
        name: "Noruega",
        code: "+47",
        iso: "NO",
        flag: getFlagUrl("no"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "41 23 45 67",
    },
    {
        name: "Nova Zelândia",
        code: "+64",
        iso: "NZ",
        flag: getFlagUrl("nz"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "21 123 4567",
    },
    {
        name: "Omã",
        code: "+968",
        iso: "OM",
        flag: getFlagUrl("om"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "9212 3456",
    },
    {
        name: "Países Baixos",
        code: "+31",
        iso: "NL",
        flag: getFlagUrl("nl"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "06 12345678",
    },
    {
        name: "Paquistão",
        code: "+92",
        iso: "PK",
        flag: getFlagUrl("pk"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "300 1234567",
    },
    {
        name: "Palau",
        code: "+680",
        iso: "PW",
        flag: getFlagUrl("pw"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "620-1234",
    },
    {
        name: "Palestina",
        code: "+970",
        iso: "PS",
        flag: getFlagUrl("ps"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "59 123 4567",
    },
    {
        name: "Panamá",
        code: "+507",
        iso: "PA",
        flag: getFlagUrl("pa"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "6123-4567",
    },
    {
        name: "Papua-Nova Guiné",
        code: "+675",
        iso: "PG",
        flag: getFlagUrl("pg"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "701 2345",
    },
    {
        name: "Paraguai",
        code: "+595",
        iso: "PY",
        flag: getFlagUrl("py"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "981 123456",
    },
    {
        name: "Peru",
        code: "+51",
        iso: "PE",
        flag: getFlagUrl("pe"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "987 654 321",
    },
    {
        name: "Polônia",
        code: "+48",
        iso: "PL",
        flag: getFlagUrl("pl"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "512 345 678",
    },
    {
        name: "Portugal",
        code: "+351",
        iso: "PT",
        flag: getFlagUrl("pt"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "912 345 678",
    },
    {
        name: "Quênia",
        code: "+254",
        iso: "KE",
        flag: getFlagUrl("ke"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "712 345678",
    },
    {
        name: "Quirguistão",
        code: "+996",
        iso: "KG",
        flag: getFlagUrl("kg"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, "-", /\d/, /\d/],
        placeholder: "700 12 34-56",
    },
    {
        name: "Reino Unido",
        code: "+44",
        iso: "GB",
        flag: getFlagUrl("gb"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "7400 123456",
    },
    {
        name: "República Centro-Africana",
        code: "+236",
        iso: "CF",
        flag: getFlagUrl("cf"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "70 12 34 56",
    },
    {
        name: "República Dominicana",
        code: "+1",
        iso: "DO",
        flag: getFlagUrl("do"),
        mask: ["(", /\d/, /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "(809) 555-1234",
    },
    {
        name: "Romênia",
        code: "+40",
        iso: "RO",
        flag: getFlagUrl("ro"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "721 234 567",
    },
    {
        name: "Ruanda",
        code: "+250",
        iso: "RW",
        flag: getFlagUrl("rw"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "788 123 456",
    },
    {
        name: "Rússia",
        code: "+7",
        iso: "RU",
        flag: getFlagUrl("ru"),
        mask: ["(", /\d/, /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, "-", /\d/, /\d/],
        placeholder: "(912) 345-67-89",
    },
    {
        name: "São Cristóvão e Neves",
        code: "+1",
        iso: "KN",
        flag: getFlagUrl("kn"),
        mask: ["(", /\d/, /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "(869) 765-4321",
    },
    {
        name: "Santa Lúcia",
        code: "+1",
        iso: "LC",
        flag: getFlagUrl("lc"),
        mask: ["(", /\d/, /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "(758) 712-3456",
    },
    {
        name: "São Marinho",
        code: "+378",
        iso: "SM",
        flag: getFlagUrl("sm"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "6666123456",
    },
    {
        name: "São Tomé e Príncipe",
        code: "+239",
        iso: "ST",
        flag: getFlagUrl("st"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "981 2345",
    },
    {
        name: "São Vicente e Granadinas",
        code: "+1",
        iso: "VC",
        flag: getFlagUrl("vc"),
        mask: ["(", /\d/, /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "(784) 430-1234",
    },
    {
        name: "Seicheles",
        code: "+248",
        iso: "SC",
        flag: getFlagUrl("sc"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "251 2345",
    },
    {
        name: "Senegal",
        code: "+221",
        iso: "SN",
        flag: getFlagUrl("sn"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "77 123 45 67",
    },
    {
        name: "Sérvia",
        code: "+381",
        iso: "RS",
        flag: getFlagUrl("rs"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "60 123 4567",
    },
    {
        name: "Singapura",
        code: "+65",
        iso: "SG",
        flag: getFlagUrl("sg"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "8123 4567",
    },
    {
        name: "Síria",
        code: "+963",
        iso: "SY",
        flag: getFlagUrl("sy"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "944 123456",
    },
    {
        name: "Somália",
        code: "+252",
        iso: "SO",
        flag: getFlagUrl("so"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "61 234 5678",
    },
    {
        name: "Sri Lanka",
        code: "+94",
        iso: "LK",
        flag: getFlagUrl("lk"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "71 234 5678",
    },
    {
        name: "Sudão",
        code: "+249",
        iso: "SD",
        flag: getFlagUrl("sd"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "91 234 5678",
    },
    {
        name: "Sudão do Sul",
        code: "+211",
        iso: "SS",
        flag: getFlagUrl("ss"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "977 123 456",
    },
    {
        name: "Suécia",
        code: "+46",
        iso: "SE",
        flag: getFlagUrl("se"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "070-123 4567",
    },
    {
        name: "Suíça",
        code: "+41",
        iso: "CH",
        flag: getFlagUrl("ch"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "79 123 45 67",
    },
    {
        name: "Suriname",
        code: "+597",
        iso: "SR",
        flag: getFlagUrl("sr"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "741-2345",
    },
    {
        name: "Tailândia",
        code: "+66",
        iso: "TH",
        flag: getFlagUrl("th"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "81 234 5678",
    },
    {
        name: "Taiwan",
        code: "+886",
        iso: "TW",
        flag: getFlagUrl("tw"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "0912-345678",
    },
    {
        name: "Tajiquistão",
        code: "+992",
        iso: "TJ",
        flag: getFlagUrl("tj"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "917 123 456",
    },
    {
        name: "Tanzânia",
        code: "+255",
        iso: "TZ",
        flag: getFlagUrl("tz"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "71 234 5678",
    },
    {
        name: "Timor-Leste",
        code: "+670",
        iso: "TL",
        flag: getFlagUrl("tl"),
        mask: [/\d/, /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "7723-4567",
    },
    {
        name: "Togo",
        code: "+228",
        iso: "TG",
        flag: getFlagUrl("tg"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "90 12 34 56",
    },
    {
        name: "Tonga",
        code: "+676",
        iso: "TO",
        flag: getFlagUrl("to"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "77123",
    },
    {
        name: "Trinidad e Tobago",
        code: "+1",
        iso: "TT",
        flag: getFlagUrl("tt"),
        mask: ["(", /\d/, /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "(868) 291-1234",
    },
    {
        name: "Tunísia",
        code: "+216",
        iso: "TN",
        flag: getFlagUrl("tn"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "20 123 456",
    },
    {
        name: "Turcomenistão",
        code: "+993",
        iso: "TM",
        flag: getFlagUrl("tm"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/],
        placeholder: "65 123-4567",
    },
    {
        name: "Turquia",
        code: "+90",
        iso: "TR",
        flag: getFlagUrl("tr"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "532 123 45 67",
    },
    {
        name: "Tuvalu",
        code: "+688",
        iso: "TV",
        flag: getFlagUrl("tv"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "90123",
    },
    {
        name: "Ucrânia",
        code: "+380",
        iso: "UA",
        flag: getFlagUrl("ua"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "67 123 45 67",
    },
    {
        name: "Uganda",
        code: "+256",
        iso: "UG",
        flag: getFlagUrl("ug"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "712 345 678",
    },
    {
        name: "Uruguai",
        code: "+598",
        iso: "UY",
        flag: getFlagUrl("uy"),
        mask: [/\d/, /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, /\d/],
        placeholder: "0912 3456",
    },
    {
        name: "Uzbequistão",
        code: "+998",
        iso: "UZ",
        flag: getFlagUrl("uz"),
        mask: [/\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/],
        placeholder: "90 123 45 67",
    },
    {
        name: "Vanuatu",
        code: "+678",
        iso: "VU",
        flag: getFlagUrl("vu"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "5912345",
    },
    {
        name: "Vaticano",
        code: "+379",
        iso: "VA",
        flag: getFlagUrl("va"),
        mask: [/\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "3123456789",
    },
    {
        name: "Venezuela",
        code: "+58",
        iso: "VE",
        flag: getFlagUrl("ve"),
        mask: [/\d/, /\d/, /\d/, "-", /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/],
        placeholder: "412-1234567",
    },
    {
        name: "Vietnã",
        code: "+84",
        iso: "VN",
        flag: getFlagUrl("vn"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "091 234 567",
    },
    {
        name: "Zâmbia",
        code: "+260",
        iso: "ZM",
        flag: getFlagUrl("zm"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "955 123 456",
    },
    {
        name: "Zimbábue",
        code: "+263",
        iso: "ZW",
        flag: getFlagUrl("zw"),
        mask: [/\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, /\d/],
        placeholder: "771 234 567",
    }
];

COUNTRY_PHONES.sort(byPriorityThenAlphabetical);

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afeganistão" },
  { code: "ZA", name: "África do Sul" },
  { code: "AL", name: "Albânia" },
  { code: "DE", name: "Alemanha" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antígua e Barbuda" },
  { code: "SA", name: "Arábia Saudita" },
  { code: "DZ", name: "Argélia" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armênia" },
  { code: "AU", name: "Austrália" },
  { code: "AT", name: "Áustria" },
  { code: "AZ", name: "Azerbaijão" },
  { code: "BS", name: "Bahamas" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BH", name: "Barein" },
  { code: "BE", name: "Bélgica" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benim" },
  { code: "BY", name: "Belarus" },
  { code: "BO", name: "Bolívia" },
  { code: "BA", name: "Bósnia e Herzegovina" },
  { code: "BW", name: "Botsuana" },
  { code: "BR", name: "Brasil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgária" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "BT", name: "Butão" },
  { code: "CV", name: "Cabo Verde" },
  { code: "CM", name: "Camarões" },
  { code: "KH", name: "Camboja" },
  { code: "CA", name: "Canadá" },
  { code: "QA", name: "Catar" },
  { code: "KZ", name: "Cazaquistão" },
  { code: "TD", name: "Chade" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CY", name: "Chipre" },
  { code: "CO", name: "Colômbia" },
  { code: "KM", name: "Comores" },
  { code: "CG", name: "Congo" },
  { code: "KP", name: "Coreia do Norte" },
  { code: "KR", name: "Coreia do Sul" },
  { code: "CI", name: "Costa do Marfim" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croácia" },
  { code: "CU", name: "Cuba" },
  { code: "DK", name: "Dinamarca" },
  { code: "DJ", name: "Djibuti" },
  { code: "DM", name: "Dominica" },
  { code: "EG", name: "Egito" },
  { code: "SV", name: "El Salvador" },
  { code: "AE", name: "Emirados Árabes Unidos" },
  { code: "EC", name: "Equador" },
  { code: "ER", name: "Eritreia" },
  { code: "SK", name: "Eslováquia" },
  { code: "SI", name: "Eslovênia" },
  { code: "ES", name: "Espanha" },
  { code: "SZ", name: "Essuatíni" },
  { code: "US", name: "Estados Unidos" },
  { code: "EE", name: "Estônia" },
  { code: "ET", name: "Etiópia" },
  { code: "FJ", name: "Fiji" },
  { code: "PH", name: "Filipinas" },
  { code: "FI", name: "Finlândia" },
  { code: "FR", name: "França" },
  { code: "GA", name: "Gabão" },
  { code: "GM", name: "Gâmbia" },
  { code: "GH", name: "Gana" },
  { code: "GE", name: "Geórgia" },
  { code: "GD", name: "Granada" },
  { code: "GR", name: "Grécia" },
  { code: "GT", name: "Guatemala" },
  { code: "GY", name: "Guiana" },
  { code: "GN", name: "Guiné" },
  { code: "GW", name: "Guiné-Bissau" },
  { code: "GQ", name: "Guiné Equatorial" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungria" },
  { code: "YE", name: "Iêmen" },
  { code: "MH", name: "Ilhas Marshall" },
  { code: "SB", name: "Ilhas Salomão" },
  { code: "IN", name: "Índia" },
  { code: "ID", name: "Indonésia" },
  { code: "IR", name: "Irã" },
  { code: "IQ", name: "Iraque" },
  { code: "IE", name: "Irlanda" },
  { code: "IS", name: "Islândia" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Itália" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japão" },
  { code: "JO", name: "Jordânia" },
  { code: "KI", name: "Kiribati" },
  { code: "XK", name: "Kosovo" },
  { code: "KW", name: "Kuwait" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesoto" },
  { code: "LV", name: "Letônia" },
  { code: "LB", name: "Líbano" },
  { code: "LR", name: "Libéria" },
  { code: "LY", name: "Líbia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituânia" },
  { code: "LU", name: "Luxemburgo" },
  { code: "MK", name: "Macedônia do Norte" },
  { code: "MG", name: "Madagascar" },
  { code: "MY", name: "Malásia" },
  { code: "MW", name: "Malawi" },
  { code: "MV", name: "Maldivas" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MA", name: "Marrocos" },
  { code: "MU", name: "Maurício" },
  { code: "MR", name: "Mauritânia" },
  { code: "MX", name: "México" },
  { code: "FM", name: "Micronésia" },
  { code: "MZ", name: "Moçambique" },
  { code: "MD", name: "Moldávia" },
  { code: "MC", name: "Mônaco" },
  { code: "MN", name: "Mongólia" },
  { code: "ME", name: "Montenegro" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namíbia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NI", name: "Nicarágua" },
  { code: "NE", name: "Níger" },
  { code: "NG", name: "Nigéria" },
  { code: "NO", name: "Noruega" },
  { code: "NZ", name: "Nova Zelândia" },
  { code: "OM", name: "Omã" },
  { code: "NL", name: "Países Baixos" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestina" },
  { code: "PA", name: "Panamá" },
  { code: "PG", name: "Papua-Nova Guiné" },
  { code: "PK", name: "Paquistão" },
  { code: "PY", name: "Paraguai" },
  { code: "PE", name: "Peru" },
  { code: "PL", name: "Polônia" },
  { code: "PT", name: "Portugal" },
  { code: "KE", name: "Quênia" },
  { code: "KG", name: "Quirguistão" },
  { code: "GB", name: "Reino Unido" },
  { code: "CF", name: "República Centro-Africana" },
  { code: "CD", name: "República Democrática do Congo" },
  { code: "DO", name: "República Dominicana" },
  { code: "CZ", name: "República Tcheca" },
  { code: "RO", name: "Romênia" },
  { code: "RW", name: "Ruanda" },
  { code: "RU", name: "Rússia" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "LC", name: "Santa Lúcia" },
  { code: "KN", name: "São Cristóvão e Névis" },
  { code: "ST", name: "São Tomé e Príncipe" },
  { code: "VC", name: "São Vicente e Granadinas" },
  { code: "SC", name: "Seicheles" },
  { code: "SN", name: "Senegal" },
  { code: "SL", name: "Serra Leoa" },
  { code: "RS", name: "Sérvia" },
  { code: "SG", name: "Singapura" },
  { code: "SY", name: "Síria" },
  { code: "SO", name: "Somália" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudão" },
  { code: "SS", name: "Sudão do Sul" },
  { code: "SE", name: "Suécia" },
  { code: "CH", name: "Suíça" },
  { code: "SR", name: "Suriname" },
  { code: "TH", name: "Tailândia" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajiquistão" },
  { code: "TZ", name: "Tanzânia" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad e Tobago" },
  { code: "TN", name: "Tunísia" },
  { code: "TM", name: "Turcomenistão" },
  { code: "TR", name: "Turquia" },
  { code: "TV", name: "Tuvalu" },
  { code: "UA", name: "Ucrânia" },
  { code: "UG", name: "Uganda" },
  { code: "UY", name: "Uruguai" },
  { code: "UZ", name: "Uzbequistão" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vaticano" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnã" },
  { code: "ZM", name: "Zâmbia" },
  { code: "ZW", name: "Zimbábue" },
] as const;

COUNTRIES.sort(byPriorityThenAlphabetical);