<?php

namespace App\Enums;

enum ServicoLogTipoEnum: string
{
    case SERVICO_CRIADO = 'SERVICO_CRIADO';
    case SERVICO_ATUALIZADO = 'SERVICO_ATUALIZADO';
    case SERVICO_ACEITO = 'SERVICO_ACEITO';
    case ACEITE_CANCELADO = 'ACEITE_CANCELADO';
    case SERVICO_RECUSADO = 'SERVICO_RECUSADO';
    case SERVICO_INICIADO = 'SERVICO_INICIADO';
    case SERVICO_INICIADO_VIA_PERICIA = 'SERVICO_INICIADO_VIA_PERICIA';
    case SERVICO_FINALIZADO = 'SERVICO_FINALIZADO';
    case SERVICO_CONCLUIDO = 'SERVICO_CONCLUIDO';
    case SERVICO_ENVIADO_RETRABALHO = 'SERVICO_ENVIADO_RETRABALHO';
    case SERVICO_CANCELADO = 'SERVICO_CANCELADO';
    case PERICIA_CRIADA = 'PERICIA_CRIADA';
    case PERICIA_ATUALIZADA = 'PERICIA_ATUALIZADA';
}
